providers = ["python"]

[variables]
PYTHON_VERSION = "3.12"

[phases.setup]
nixPkgs = ["uv"]

[phases.install]
cmds = ["uv sync --frozen"]

[start]
cmd = "uv run uvicorn main:app --host 0.0.0.0 --port $PORT"