[project]
name = "fast-rail"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-fasthtml>=0.12.24",
    "uvicorn>=0.35.0",
]
